"""init db

Revision ID: 50523919eb00
Revises: 
Create Date: 2026-04-17 15:18:29.736050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from core.types.guid import GUID

# IMPORTANT: Do not import models directly in migration files.
# The env.py file handles all model imports and database URL conversion.
# If you need to reference model classes, use string references instead.

# revision identifiers, used by Alembic.
revision: str = '50523919eb00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create schemas first
    op.execute('CREATE SCHEMA IF NOT EXISTS account')
    op.execute('CREATE SCHEMA IF NOT EXISTS academic')
    op.execute('CREATE SCHEMA IF NOT EXISTS analytics')
    op.execute('CREATE SCHEMA IF NOT EXISTS billings')
    
    op.create_table('answers',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('value', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', name='answer_enum'), nullable=True, comment='MCQ answer: option letter a-z'),
    sa.Column('text_value', sa.String(length=500), nullable=True, comment='FITB answer: correct text answer (case-insensitive match)'),
    sa.Column('acceptable_variations', sa.JSON(), nullable=True, comment='FITB: acceptable answer variations, e.g., ["Photosynthesis", "photosynthesis"]'),
    sa.Column('answer_type', sa.String(length=20), server_default='mcq', nullable=False, comment='Answer type: mcq|fitb'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index('ix_answers_created_at', 'answers', ['created_at'], unique=False, schema='academic')
    op.create_index('ix_answers_id', 'answers', ['id'], unique=False, schema='academic')
    op.create_table('tenants',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Tenant display name'),
    sa.Column('domain', sa.String(length=255), nullable=True, comment='Canonical domain, e.g. example.edu'),
    sa.Column('logo_url', sa.String(length=255), nullable=True, comment='Optional logo URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Tenant enabled flag'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='account'
    )
    op.create_index('ix_tenants_created_at', 'tenants', ['created_at'], unique=False, schema='account')
    op.create_index('ix_tenants_domain', 'tenants', ['domain'], unique=True, schema='account')
    op.create_index('ix_tenants_is_active', 'tenants', ['is_active'], unique=False, schema='account')
    op.create_index('ix_tenants_name', 'tenants', ['name'], unique=False, schema='account')
    op.create_index('ix_tenants_updated_at', 'tenants', ['updated_at'], unique=False, schema='account')
    op.create_table('users',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Given name'),
    sa.Column('middle_name', sa.String(length=100), nullable=True, comment='Middle name, optional'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Family name'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Login email (unique)'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Hashed password'),
    sa.Column('role', sa.Enum('student', 'lecturer', 'admin', 'superadmin', name='user_role'), nullable=False, comment='User role enum'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active flag'),
    sa.Column('tenant_id', GUID(length=16), nullable=True, comment='FK: tenant id for multi-tenancy'),
    sa.Column('institution_id', sa.String(length=100), nullable=True, comment='Institution ID e.g., Student matric/registration number'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='account'
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False, schema='account')
    op.create_index('ix_users_email', 'users', ['email'], unique=False, schema='account')
    op.create_index('ix_users_email_tenant', 'users', ['email', 'tenant_id'], unique=False, schema='account')
    op.create_index('ix_users_institution_id', 'users', ['institution_id'], unique=False, schema='account')
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False, schema='account')
    op.create_index('ix_users_role', 'users', ['role'], unique=False, schema='account')
    op.create_index('ix_users_tenant_active', 'users', ['tenant_id', 'is_active'], unique=False, schema='account')
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False, schema='account')
    op.create_index('ix_users_tenant_institution', 'users', ['tenant_id', 'institution_id'], unique=False, schema='account')
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False, schema='account')
    op.create_index('ix_users_updated_at', 'users', ['updated_at'], unique=False, schema='account')
    op.create_table('courses',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Course name'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Optional course description'),
    sa.Column('course_code', sa.String(length=20), nullable=False, comment='Short course code'),
    sa.Column('lecturer_id', GUID(length=16), nullable=True, comment='FK to users (lecturer)'),
    sa.Column('tenant_id', GUID(length=16), nullable=True, comment='FK to tenants (organization)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (timezone-aware)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (timezone-aware)'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['account.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['account.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_courses_name'), 'courses', ['name'], unique=False, schema='academic')
    op.create_index('ix_courses_course_code', 'courses', ['course_code'], unique=True, schema='academic')
    op.create_index('ix_courses_created_at', 'courses', ['created_at'], unique=False, schema='academic')
    op.create_index('ix_courses_lecturer_id', 'courses', ['lecturer_id'], unique=False, schema='academic')
    op.create_index('ix_courses_lecturer_tenant', 'courses', ['lecturer_id', 'tenant_id'], unique=False, schema='academic')
    op.create_index('ix_courses_tenant_code', 'courses', ['tenant_id', 'course_code'], unique=False, schema='academic')
    op.create_index('ix_courses_tenant_created', 'courses', ['tenant_id', 'created_at'], unique=False, schema='academic')
    op.create_index('ix_courses_tenant_id', 'courses', ['tenant_id'], unique=False, schema='academic')
    op.create_index('ix_courses_updated_at', 'courses', ['updated_at'], unique=False, schema='academic')
    op.create_table('questions',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('number', sa.String(length=20), nullable=False, comment='Question number within the exam'),
    sa.Column('text', sa.String(length=2000), nullable=False, comment='Question text'),
    sa.Column('images', sa.JSON(), nullable=True, comment='Optional array of image URLs for the question'),
    sa.Column('parent_id', GUID(length=16), nullable=True, comment='Optional FK to parent question for sub-questions'),
    sa.Column('tenant_id', GUID(length=16), nullable=True, comment='Optional FK to tenant/organization'),
    sa.Column('rules', sa.String(length=2000), nullable=True, comment='Optional grading rules or metadata in JSON format'),
    sa.Column('mark', sa.Numeric(precision=10, scale=2), nullable=True, comment='Mark for the question'),
    sa.Column('industry', sa.Enum('MEDICAL_AND_HEALTH_SCIENCES', 'NATURAL_SCIENCES', 'MATHEMATICS_AND_STATISTICS', 'ENGINEERING_AND_TECHNOLOGY', 'COMPUTING_AND_INFORMATION_TECHNOLOGY', 'BUSINESS_AND_MANAGEMENT', 'ECONOMICS_AND_FINANCE', 'LAW_AND_GOVERNANCE', 'SOCIAL_SCIENCES', 'HUMANITIES', 'ARTS_AND_DESIGN', 'MEDIA_AND_COMMUNICATION', 'EDUCATION', 'SPORTS_AND_PHYSICAL_EDUCATION', 'AGRICULTURE_AND_FOOD_SCIENCE', 'ENVIRONMENT_AND_SUSTAINABILITY', 'VOCATIONAL_AND_APPLIED', 'GENERAL', name='industry_enum'), nullable=False, comment='Industry/subject area of the question'),
    sa.Column('qtype', sa.String(length=50), server_default='theory', nullable=False, comment='Question type: multiple_choice|theory|fill_in_blanks'),
    sa.Column('options', sa.JSON(), nullable=True, comment='Options JSON list, e.g. [{"label":"a","text":"Option A"}]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answer_id', GUID(length=16), nullable=True, comment='Optional FK to an Answer shared across questions'),
    sa.CheckConstraint("qtype IN ('multiple_choice','theory','fill_in_blanks')", name='ck_questions_qtype'),
    sa.ForeignKeyConstraint(['answer_id'], ['academic.answers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['academic.questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['account.tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index('ix_questions_answer_id', 'questions', ['answer_id'], unique=False, schema='academic')
    op.create_index('ix_questions_created_at', 'questions', ['created_at'], unique=False, schema='academic')
    op.create_index('ix_questions_industry', 'questions', ['industry'], unique=False, schema='academic')
    op.create_index('ix_questions_parent_id', 'questions', ['parent_id'], unique=False, schema='academic')
    op.create_index('ix_questions_parent_qtype', 'questions', ['parent_id', 'qtype'], unique=False, schema='academic')
    op.create_index('ix_questions_qtype', 'questions', ['qtype'], unique=False, schema='academic')
    op.create_index('ix_questions_tenant_created_at', 'questions', ['tenant_id', 'created_at'], unique=False, schema='academic')
    op.create_index('ix_questions_tenant_id', 'questions', ['tenant_id'], unique=False, schema='academic')
    op.create_index('ix_questions_tenant_industry', 'questions', ['tenant_id', 'industry'], unique=False, schema='academic')
    op.create_index('ix_questions_tenant_qtype', 'questions', ['tenant_id', 'qtype'], unique=False, schema='academic')
    op.create_index('ix_questions_updated_at', 'questions', ['updated_at'], unique=False, schema='academic')
    op.create_table('oauth',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7'),
    sa.Column('user_id', GUID(length=16), nullable=False, comment='FK to users'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment="OAuth provider name, e.g. 'google', 'facebook'"),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='User ID from the OAuth provider'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user'),
    schema='account'
    )
    op.create_index('ix_oauth_user_id_provider', 'oauth', ['user_id', 'provider'], unique=False, schema='account')
    op.create_table('tenant_admins',
    sa.Column('tenant_id', GUID(length=16), nullable=False),
    sa.Column('user_id', GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['account.tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id'),
    schema='account'
    )
    op.create_table('admin_dashboard',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('admin_id', GUID(length=16), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('total_lecturers', sa.Integer(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('total_courses', sa.Integer(), nullable=False),
    sa.Column('total_exams', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('total_graded_submissions', sa.Integer(), nullable=False),
    sa.Column('total_pending_submissions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', name='uq_admin_dashboard_admin_id'),
    schema='analytics'
    )
    op.create_index('ix_admin_dashboard_created_at', 'admin_dashboard', ['created_at'], unique=False, schema='analytics')
    op.create_index('ix_admin_dashboard_updated_at', 'admin_dashboard', ['updated_at'], unique=False, schema='analytics')
    op.create_table('lecturer_dashboard',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('lecturer_id', GUID(length=16), nullable=False),
    sa.Column('total_courses', sa.Integer(), nullable=False),
    sa.Column('total_exams', sa.Integer(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('pending_submissions', sa.Integer(), nullable=False),
    sa.Column('graded_submissions', sa.Integer(), nullable=False),
    sa.Column('active_courses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lecturer_id', name='uq_lecturer_dashboard_lecturer_id'),
    schema='analytics'
    )
    op.create_index('ix_lecturer_dashboard_created_at', 'lecturer_dashboard', ['created_at'], unique=False, schema='analytics')
    op.create_index('ix_lecturer_dashboard_updated_at', 'lecturer_dashboard', ['updated_at'], unique=False, schema='analytics')
    op.create_table('student_dashboard',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('student_id', GUID(length=16), nullable=False),
    sa.Column('total_courses', sa.Integer(), nullable=False),
    sa.Column('total_exams', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('total_graded_submissions', sa.Integer(), nullable=False),
    sa.Column('total_pending_submissions', sa.Integer(), nullable=False),
    sa.Column('missed_exams', sa.Integer(), nullable=False),
    sa.Column('upcoming_exams', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', name='uq_student_dashboard_student_id'),
    schema='analytics'
    )
    op.create_index('ix_student_dashboard_created_at', 'student_dashboard', ['created_at'], unique=False, schema='analytics')
    op.create_index('ix_student_dashboard_updated_at', 'student_dashboard', ['updated_at'], unique=False, schema='analytics')
    op.create_table('current_usage',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('student_count', sa.Integer(), nullable=False, comment='Number of students'),
    sa.Column('exams_graded', sa.Integer(), nullable=False, comment='Number of exams graded'),
    sa.Column('plan', sa.Enum('STARTER', 'INTERMEDIATE', 'ENTERPRISE', name='plantype'), nullable=False, comment='Current plan type'),
    sa.Column('tenant_id', GUID(length=16), nullable=False, comment='Tenant ID'),
    sa.Column('plan_updated_at', sa.DateTime(timezone=True), nullable=False, comment='When the plan was last updated'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the record was last updated'),
    sa.CheckConstraint('exams_graded >= 0', name='check_exams_graded_non_negative'),
    sa.CheckConstraint('student_count >= 0', name='check_student_count_non_negative'),
    sa.ForeignKeyConstraint(['tenant_id'], ['account.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billings'
    )
    op.create_index('ix_current_usage_created_at', 'current_usage', ['created_at'], unique=False, schema='billings')
    op.create_index('ix_current_usage_plan', 'current_usage', ['plan'], unique=False, schema='billings')
    op.create_index('ix_current_usage_tenant_id', 'current_usage', ['tenant_id'], unique=False, schema='billings')
    op.create_index('ix_current_usage_tenant_plan', 'current_usage', ['tenant_id', 'plan'], unique=False, schema='billings')
    op.create_index('ix_current_usage_updated_at', 'current_usage', ['updated_at'], unique=False, schema='billings')
    op.create_table('invoices',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('student_count', sa.Integer(), nullable=False, comment='Number of students'),
    sa.Column('amount_per_student', sa.Integer(), nullable=False, comment='Amount per student'),
    sa.Column('total_amount', sa.Integer(), nullable=False, comment='Total amount'),
    sa.Column('tenant_id', GUID(length=16), nullable=False, comment='Tenant ID'),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='invoicestatus'), nullable=False, comment='Invoice status'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the record was last updated'),
    sa.CheckConstraint('amount_per_student >= 0', name='check_amount_per_student_non_negative'),
    sa.CheckConstraint('student_count >= 0', name='check_invoice_student_count_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='check_total_amount_non_negative'),
    sa.ForeignKeyConstraint(['tenant_id'], ['account.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billings'
    )
    op.create_index('ix_invoice_created_at', 'invoices', ['created_at'], unique=False, schema='billings')
    op.create_index('ix_invoice_status', 'invoices', ['status'], unique=False, schema='billings')
    op.create_index('ix_invoice_tenant_id', 'invoices', ['tenant_id'], unique=False, schema='billings')
    op.create_index('ix_invoice_tenant_status', 'invoices', ['tenant_id', 'status'], unique=False, schema='billings')
    op.create_index('ix_invoice_updated_at', 'invoices', ['updated_at'], unique=False, schema='billings')
    op.create_table('payment_methods',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('type', sa.Enum('CREDIT_CARD', 'PAYPAL', 'BANK_TRANSFER', 'OTHER', name='paymentmethodtype'), nullable=False, comment='Payment method type'),
    sa.Column('tenant_id', GUID(length=16), nullable=False, comment='Tenant ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['account.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billings'
    )
    op.create_index('ix_payment_methods_created_at', 'payment_methods', ['created_at'], unique=False, schema='billings')
    op.create_index('ix_payment_methods_tenant_id', 'payment_methods', ['tenant_id'], unique=False, schema='billings')
    op.create_index('ix_payment_methods_tenant_type', 'payment_methods', ['tenant_id', 'type'], unique=False, schema='billings')
    op.create_index('ix_payment_methods_type', 'payment_methods', ['type'], unique=False, schema='billings')
    op.create_index('ix_payment_methods_updated_at', 'payment_methods', ['updated_at'], unique=False, schema='billings')
    op.create_table('enrollments',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('student_id', GUID(length=16), nullable=False, comment='FK: Student user ID'),
    sa.Column('course_id', GUID(length=16), nullable=False, comment='FK: Course ID'),
    sa.Column('semester', sa.Enum('FALL', 'SPRING', 'SUMMER', 'WINTER', 'INTERIM', 'FIRST', 'SECOND', 'THIRD', 'FOURTH', 'FIFTH', 'SIXTH', 'SEVENTH', 'EIGHTH', name='semester_enum'), nullable=False, comment='Academic semester'),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DROPPED', 'PENDING', name='enrollment_status'), nullable=False, comment='Current enrollment status'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (timezone-aware)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (timezone-aware)'),
    sa.ForeignKeyConstraint(['course_id'], ['academic.courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_student_course'),
    schema='academic'
    )
    op.create_index('ix_enrollment_course_id', 'enrollments', ['course_id'], unique=False, schema='academic')
    op.create_index('ix_enrollment_course_status', 'enrollments', ['course_id', 'status'], unique=False, schema='academic')
    op.create_index('ix_enrollment_created_at', 'enrollments', ['created_at'], unique=False, schema='academic')
    op.create_index('ix_enrollment_semester', 'enrollments', ['semester'], unique=False, schema='academic')
    op.create_index('ix_enrollment_status', 'enrollments', ['status'], unique=False, schema='academic')
    op.create_index('ix_enrollment_student_course', 'enrollments', ['student_id', 'course_id'], unique=False, schema='academic')
    op.create_index('ix_enrollment_student_semester', 'enrollments', ['student_id', 'semester'], unique=False, schema='academic')
    op.create_index('ix_enrollment_student_status', 'enrollments', ['student_id', 'status'], unique=False, schema='academic')
    op.create_index('ix_enrollment_tenant_semester_status', 'enrollments', ['student_id', 'semester', 'status'], unique=False, schema='academic')
    op.create_index('ix_enrollment_updated_at', 'enrollments', ['updated_at'], unique=False, schema='academic')
    op.create_table('exams',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Exam title'),
    sa.Column('description', sa.String(length=2000), nullable=True, comment='Exam description'),
    sa.Column('duration', sa.Numeric(precision=5, scale=2), nullable=False, comment='Duration in hours (decimal)'),
    sa.Column('total_marks', sa.Integer(), nullable=True, comment='Total marks for the exam'),
    sa.Column('passing_marks', sa.Integer(), nullable=True, comment='Passing marks for the exam'),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'FINISHED', name='exam_status'), nullable=True, comment='Exam status: not_started, in_progress, finished'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='Exam start time (timezone-aware)'),
    sa.Column('max_attempts', sa.Integer(), nullable=False, comment='Maximum attempts allowed (default 1)'),
    sa.Column('course_id', GUID(length=16), nullable=True, comment='FK to course'),
    sa.Column('tenant_id', GUID(length=16), nullable=True, comment='FK to tenant/organization'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', GUID(length=16), nullable=True, comment='User who created'),
    sa.Column('updated_by', GUID(length=16), nullable=True, comment='User who last updated'),
    sa.CheckConstraint('duration > 0', name='ck_exams_duration_positive'),
    sa.CheckConstraint('max_attempts > 0', name='ck_exams_max_attempts_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['academic.courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['account.tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['account.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index('ix_exams_course_id', 'exams', ['course_id'], unique=False, schema='academic')
    op.create_index('ix_exams_course_start_time', 'exams', ['course_id', 'start_time'], unique=False, schema='academic')
    op.create_index('ix_exams_course_status', 'exams', ['course_id', 'status'], unique=False, schema='academic')
    op.create_index('ix_exams_created_at', 'exams', ['created_at'], unique=False, schema='academic')
    op.create_index('ix_exams_created_by', 'exams', ['created_by'], unique=False, schema='academic')
    op.create_index('ix_exams_start_time', 'exams', ['start_time'], unique=False, schema='academic')
    op.create_index('ix_exams_status', 'exams', ['status'], unique=False, schema='academic')
    op.create_index('ix_exams_tenant_id', 'exams', ['tenant_id'], unique=False, schema='academic')
    op.create_index('ix_exams_tenant_start_time', 'exams', ['tenant_id', 'start_time'], unique=False, schema='academic')
    op.create_index('ix_exams_tenant_status', 'exams', ['tenant_id', 'status'], unique=False, schema='academic')
    op.create_index('ix_exams_updated_at', 'exams', ['updated_at'], unique=False, schema='academic')
    op.create_index('ix_exams_updated_by', 'exams', ['updated_by'], unique=False, schema='academic')
    op.create_table('payment_method_details',
    sa.Column('id', GUID(length=16), nullable=False, comment='Primary key: UUIDv7 time-ordered'),
    sa.Column('payment_method_id', GUID(length=16), nullable=False, comment='Foreign key to payment_methods'),
    sa.Column('details', sa.JSON(), nullable=False, comment='Payment method details'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the record was last updated'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['billings.payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billings'
    )
    op.create_index('ix_payment_method_details_created_at', 'payment_method_details', ['created_at'], unique=False, schema='billings')
    op.create_index('ix_payment_method_details_payment_method_id', 'payment_method_details', ['payment_method_id'], unique=False, schema='billings')
    op.create_table('question_exams',
    sa.Column('question_id', GUID(length=16), nullable=False, comment='FK to question'),
    sa.Column('exam_id', GUID(length=16), nullable=False, comment='FK to exam'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['academic.exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['academic.questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'exam_id'),
    schema='academic'
    )
    op.create_index('ix_question_exams_exam_id', 'question_exams', ['exam_id'], unique=False, schema='academic')
    op.create_index('ix_question_exams_question_id', 'question_exams', ['question_id'], unique=False, schema='academic')
    op.create_table('student_answers',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('student_id', GUID(length=16), nullable=False),
    sa.Column('exam_id', GUID(length=16), nullable=False),
    sa.Column('question_id', GUID(length=16), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False, comment="Student's in-progress answer JSON"),
    sa.Column('last_saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['academic.exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['academic.questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['account.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index('ix_student_answers_created_at', 'student_answers', ['created_at'], unique=False, schema='academic')
    op.create_index('ix_student_answers_exam_id', 'student_answers', ['exam_id'], unique=False, schema='academic')
    op.create_index('ix_student_answers_exam_question', 'student_answers', ['exam_id', 'question_id'], unique=False, schema='academic')
    op.create_index('ix_student_answers_last_saved_at', 'student_answers', ['last_saved_at'], unique=False, schema='academic')
    op.create_index('ix_student_answers_question_id', 'student_answers', ['question_id'], unique=False, schema='academic')
    op.create_index('ix_student_answers_student_exam', 'student_answers', ['student_id', 'exam_id'], unique=False, schema='academic')
    op.create_index('ix_student_answers_student_id', 'student_answers', ['student_id'], unique=False, schema='academic')
    op.create_index('ix_student_answers_student_question', 'student_answers', ['student_id', 'question_id'], unique=False, schema='academic')
    op.create_table('submissions',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('student_id', GUID(length=16), nullable=False),
    sa.Column('exam_id', GUID(length=16), nullable=False),
    sa.Column('latest_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(latest_score IS NULL) OR (latest_score >= 0)', name='ck_submissions_latest_score_nonnegative'),
    sa.CheckConstraint('attempts_count >= 0', name='ck_submissions_attempts_nonnegative'),
    sa.ForeignKeyConstraint(['exam_id'], ['academic.exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['account.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index('ix_submissions_created_at', 'submissions', ['created_at'], unique=False, schema='academic')
    op.create_index('ix_submissions_exam_graded', 'submissions', ['exam_id', 'graded_at'], unique=False, schema='academic')
    op.create_index('ix_submissions_exam_id', 'submissions', ['exam_id'], unique=False, schema='academic')
    op.create_index('ix_submissions_graded_at', 'submissions', ['graded_at'], unique=False, schema='academic')
    op.create_index('ix_submissions_student_graded', 'submissions', ['student_id', 'graded_at'], unique=False, schema='academic')
    op.create_index('ix_submissions_student_id', 'submissions', ['student_id'], unique=False, schema='academic')
    op.create_index('ix_submissions_updated_at', 'submissions', ['updated_at'], unique=False, schema='academic')
    op.create_index('uq_submissions_student_exam', 'submissions', ['student_id', 'exam_id'], unique=True, schema='academic')
    op.create_table('submission_attempts',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('submission_id', GUID(length=16), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('scan_pages', sa.JSON(), nullable=True, comment='List of scanned page URLs for offline exams'),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(score IS NULL) OR (score >= 0)', name='ck_submission_attempts_score_nonneg'),
    sa.ForeignKeyConstraint(['submission_id'], ['academic.submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index('ix_submission_attempts_created_at', 'submission_attempts', ['created_at'], unique=False, schema='academic')
    op.create_index('ix_submission_attempts_graded_at', 'submission_attempts', ['graded_at'], unique=False, schema='academic')
    op.create_index('ix_submission_attempts_submission_attempt', 'submission_attempts', ['submission_id', 'attempt_number'], unique=True, schema='academic')
    op.create_index('ix_submission_attempts_submission_id', 'submission_attempts', ['submission_id'], unique=False, schema='academic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_attempts_submission_id', table_name='submission_attempts', schema='academic')
    op.drop_index('ix_submission_attempts_submission_attempt', table_name='submission_attempts', schema='academic')
    op.drop_index('ix_submission_attempts_graded_at', table_name='submission_attempts', schema='academic')
    op.drop_index('ix_submission_attempts_created_at', table_name='submission_attempts', schema='academic')
    op.drop_table('submission_attempts', schema='academic')
    op.drop_index('uq_submissions_student_exam', table_name='submissions', schema='academic')
    op.drop_index('ix_submissions_updated_at', table_name='submissions', schema='academic')
    op.drop_index('ix_submissions_student_id', table_name='submissions', schema='academic')
    op.drop_index('ix_submissions_student_graded', table_name='submissions', schema='academic')
    op.drop_index('ix_submissions_graded_at', table_name='submissions', schema='academic')
    op.drop_index('ix_submissions_exam_id', table_name='submissions', schema='academic')
    op.drop_index('ix_submissions_exam_graded', table_name='submissions', schema='academic')
    op.drop_index('ix_submissions_created_at', table_name='submissions', schema='academic')
    op.drop_table('submissions', schema='academic')
    op.drop_index('ix_student_answers_student_question', table_name='student_answers', schema='academic')
    op.drop_index('ix_student_answers_student_id', table_name='student_answers', schema='academic')
    op.drop_index('ix_student_answers_student_exam', table_name='student_answers', schema='academic')
    op.drop_index('ix_student_answers_question_id', table_name='student_answers', schema='academic')
    op.drop_index('ix_student_answers_last_saved_at', table_name='student_answers', schema='academic')
    op.drop_index('ix_student_answers_exam_question', table_name='student_answers', schema='academic')
    op.drop_index('ix_student_answers_exam_id', table_name='student_answers', schema='academic')
    op.drop_index('ix_student_answers_created_at', table_name='student_answers', schema='academic')
    op.drop_table('student_answers', schema='academic')
    op.drop_index('ix_question_exams_question_id', table_name='question_exams', schema='academic')
    op.drop_index('ix_question_exams_exam_id', table_name='question_exams', schema='academic')
    op.drop_table('question_exams', schema='academic')
    op.drop_index('ix_payment_method_details_payment_method_id', table_name='payment_method_details', schema='billings')
    op.drop_index('ix_payment_method_details_created_at', table_name='payment_method_details', schema='billings')
    op.drop_table('payment_method_details', schema='billings')
    op.drop_index('ix_exams_updated_by', table_name='exams', schema='academic')
    op.drop_index('ix_exams_updated_at', table_name='exams', schema='academic')
    op.drop_index('ix_exams_tenant_status', table_name='exams', schema='academic')
    op.drop_index('ix_exams_tenant_start_time', table_name='exams', schema='academic')
    op.drop_index('ix_exams_tenant_id', table_name='exams', schema='academic')
    op.drop_index('ix_exams_status', table_name='exams', schema='academic')
    op.drop_index('ix_exams_start_time', table_name='exams', schema='academic')
    op.drop_index('ix_exams_created_by', table_name='exams', schema='academic')
    op.drop_index('ix_exams_created_at', table_name='exams', schema='academic')
    op.drop_index('ix_exams_course_status', table_name='exams', schema='academic')
    op.drop_index('ix_exams_course_start_time', table_name='exams', schema='academic')
    op.drop_index('ix_exams_course_id', table_name='exams', schema='academic')
    op.drop_table('exams', schema='academic')
    op.drop_index('ix_enrollment_updated_at', table_name='enrollments', schema='academic')
    op.drop_index('ix_enrollment_tenant_semester_status', table_name='enrollments', schema='academic')
    op.drop_index('ix_enrollment_student_status', table_name='enrollments', schema='academic')
    op.drop_index('ix_enrollment_student_semester', table_name='enrollments', schema='academic')
    op.drop_index('ix_enrollment_student_course', table_name='enrollments', schema='academic')
    op.drop_index('ix_enrollment_status', table_name='enrollments', schema='academic')
    op.drop_index('ix_enrollment_semester', table_name='enrollments', schema='academic')
    op.drop_index('ix_enrollment_created_at', table_name='enrollments', schema='academic')
    op.drop_index('ix_enrollment_course_status', table_name='enrollments', schema='academic')
    op.drop_index('ix_enrollment_course_id', table_name='enrollments', schema='academic')
    op.drop_table('enrollments', schema='academic')
    op.drop_index('ix_payment_methods_updated_at', table_name='payment_methods', schema='billings')
    op.drop_index('ix_payment_methods_type', table_name='payment_methods', schema='billings')
    op.drop_index('ix_payment_methods_tenant_type', table_name='payment_methods', schema='billings')
    op.drop_index('ix_payment_methods_tenant_id', table_name='payment_methods', schema='billings')
    op.drop_index('ix_payment_methods_created_at', table_name='payment_methods', schema='billings')
    op.drop_table('payment_methods', schema='billings')
    op.drop_index('ix_invoice_updated_at', table_name='invoices', schema='billings')
    op.drop_index('ix_invoice_tenant_status', table_name='invoices', schema='billings')
    op.drop_index('ix_invoice_tenant_id', table_name='invoices', schema='billings')
    op.drop_index('ix_invoice_status', table_name='invoices', schema='billings')
    op.drop_index('ix_invoice_created_at', table_name='invoices', schema='billings')
    op.drop_table('invoices', schema='billings')
    op.drop_index('ix_current_usage_updated_at', table_name='current_usage', schema='billings')
    op.drop_index('ix_current_usage_tenant_plan', table_name='current_usage', schema='billings')
    op.drop_index('ix_current_usage_tenant_id', table_name='current_usage', schema='billings')
    op.drop_index('ix_current_usage_plan', table_name='current_usage', schema='billings')
    op.drop_index('ix_current_usage_created_at', table_name='current_usage', schema='billings')
    op.drop_table('current_usage', schema='billings')
    op.drop_index('ix_student_dashboard_updated_at', table_name='student_dashboard', schema='analytics')
    op.drop_index('ix_student_dashboard_student_id', table_name='student_dashboard', schema='analytics')
    op.drop_index('ix_student_dashboard_created_at', table_name='student_dashboard', schema='analytics')
    op.drop_table('student_dashboard', schema='analytics')
    op.drop_index('ix_lecturer_dashboard_updated_at', table_name='lecturer_dashboard', schema='analytics')
    op.drop_index('ix_lecturer_dashboard_lecturer_id', table_name='lecturer_dashboard', schema='analytics')
    op.drop_index('ix_lecturer_dashboard_created_at', table_name='lecturer_dashboard', schema='analytics')
    op.drop_table('lecturer_dashboard', schema='analytics')
    op.drop_index('ix_admin_dashboard_updated_at', table_name='admin_dashboard', schema='analytics')
    op.drop_index('ix_admin_dashboard_created_at', table_name='admin_dashboard', schema='analytics')
    op.drop_index('ix_admin_dashboard_admin_id', table_name='admin_dashboard', schema='analytics')
    op.drop_table('admin_dashboard', schema='analytics')
    op.drop_table('tenant_admins', schema='account')
    op.drop_index('ix_oauth_user_id_provider', table_name='oauth', schema='account')
    op.drop_table('oauth', schema='account')
    op.drop_index('ix_questions_updated_at', table_name='questions', schema='academic')
    op.drop_index('ix_questions_tenant_qtype', table_name='questions', schema='academic')
    op.drop_index('ix_questions_tenant_industry', table_name='questions', schema='academic')
    op.drop_index('ix_questions_tenant_id', table_name='questions', schema='academic')
    op.drop_index('ix_questions_tenant_created_at', table_name='questions', schema='academic')
    op.drop_index('ix_questions_qtype', table_name='questions', schema='academic')
    op.drop_index('ix_questions_parent_qtype', table_name='questions', schema='academic')
    op.drop_index('ix_questions_parent_id', table_name='questions', schema='academic')
    op.drop_index('ix_questions_industry', table_name='questions', schema='academic')
    op.drop_index('ix_questions_created_at', table_name='questions', schema='academic')
    op.drop_index('ix_questions_answer_id', table_name='questions', schema='academic')
    op.drop_table('questions', schema='academic')
    op.drop_index('ix_courses_updated_at', table_name='courses', schema='academic')
    op.drop_index('ix_courses_tenant_id', table_name='courses', schema='academic')
    op.drop_index('ix_courses_tenant_created', table_name='courses', schema='academic')
    op.drop_index('ix_courses_tenant_code', table_name='courses', schema='academic')
    op.drop_index('ix_courses_lecturer_tenant', table_name='courses', schema='academic')
    op.drop_index('ix_courses_lecturer_id', table_name='courses', schema='academic')
    op.drop_index('ix_courses_created_at', table_name='courses', schema='academic')
    op.drop_index('ix_courses_course_code', table_name='courses', schema='academic')
    op.drop_index(op.f('ix_academic_courses_name'), table_name='courses', schema='academic')
    op.drop_table('courses', schema='academic')
    op.drop_index('ix_users_updated_at', table_name='users', schema='account')
    op.drop_index('ix_users_tenant_role', table_name='users', schema='account')
    op.drop_index('ix_users_tenant_institution', table_name='users', schema='account')
    op.drop_index('ix_users_tenant_id', table_name='users', schema='account')
    op.drop_index('ix_users_tenant_active', table_name='users', schema='account')
    op.drop_index('ix_users_role', table_name='users', schema='account')
    op.drop_index('ix_users_is_active', table_name='users', schema='account')
    op.drop_index('ix_users_institution_id', table_name='users', schema='account')
    op.drop_index('ix_users_email_tenant', table_name='users', schema='account')
    op.drop_index('ix_users_email', table_name='users', schema='account')
    op.drop_index('ix_users_created_at', table_name='users', schema='account')
    op.drop_table('users', schema='account')
    op.drop_index('ix_tenants_updated_at', table_name='tenants', schema='account')
    op.drop_index('ix_tenants_name', table_name='tenants', schema='account')
    op.drop_index('ix_tenants_is_active', table_name='tenants', schema='account')
    op.drop_index('ix_tenants_domain', table_name='tenants', schema='account')
    op.drop_index('ix_tenants_created_at', table_name='tenants', schema='account')
    op.drop_table('tenants', schema='account')
    op.drop_index('ix_answers_id', table_name='answers', schema='academic')
    op.drop_index('ix_answers_created_at', table_name='answers', schema='academic')
    op.drop_table('answers', schema='academic')
    # ### end Alembic commands ###
