/** Known Nigerian universities mapping to their abbreviations */
export const NIGERIAN_UNIVERSITIES: Record<string, string> = {
  'university of benin': 'U.N.I.B.E.N.',
  'university of lagos': 'U.N.I.L.A.G.',
  'university of ibadan': 'U.I.',
  'university of nigeria': 'U.N.N.',
  'university of port harcourt': 'U.N.I.P.O.R.T.',
  'ahmadu bello university': 'A.B.U.',
  'obafemi awolowo university': 'O.A.U.',
  'university of ilorin': 'U.N.I.L.O.R.I.N.',
  'university of abuja': 'U.N.I.A.B.U.J.A.',
  'university of jos': 'U.N.I.J.O.S.',
  'university of maiduguri': 'U.N.I.M.A.I.D.',
  'university of calabar': 'U.N.I.C.A.L.',
  'university of uyo': 'U.N.I.U.Y.O.',
  'lagos state university': 'L.A.S.U.',
  'olabisi onabanjo university': 'O.O.U.',
  'ekiti state university': 'E.K.S.U.',
  'delta state university': 'D.E.L.S.U.',
  'rivers state university': 'R.S.U.',
  'imo state university': 'I.M.S.U.',
  'anambra state university': 'A.N.S.U.',
  'nasarawa state university': 'N.A.S.U.',
  'niger delta university': 'N.D.U.',
  'ambrose alli university': 'A.A.U.',
  'enugu state university': 'E.S.U.T.',
  'abia state university': 'A.B.S.U.',
  'kwara state university': 'K.W.A.S.U.',
  'adekunle ajasin university': 'A.A.U.A.',
  'bayero university': 'B.U.K.',
  'usmanu danfodiyo university': 'U.D.U.S.O.K.',
  'nnamdi azikiwe university': 'U.N.I.Z.I.K.',
  'michael okpara university': 'M.O.A.U.',
  'ibrahim badamasi babangida university': 'I.B.B.U.',
  'modibbo adama university': 'M.A.U.',
  'federal university of technology akure': 'F.U.T.A.',
  'federal university of technology minna': 'F.U.T.M.I.N.N.A.',
  'federal university of technology owerri': 'F.U.T.O.',
  'federal university dutsin-ma': 'F.U.D.',
  'federal university lokoja': 'F.U.L.',
  'federal university ndifu-alike': 'F.U.N.A.I.',
  'federal university otuoke': 'F.U.O.',
  'federal university wukari': 'F.U.W.',
  'federal university gashua': 'F.U.G.',
  'federal university birnin kebbi': 'F.U.B.K.',
  'federal university gusau': 'F.U.G.U.S.A.U.',
  'federal university kashere': 'F.U.K.',
  'federal university lafia': 'F.U.L.A.F.I.A.',
  'federal university ndufu-alike': 'F.U.N.A.I.',
  'university of medical sciences': 'U.N.I.M.E.D.',
  'nigeria police academy': 'N.P.A.',
  'nigerian defence academy': 'N.D.A.',

  // ========== PRIVATE UNIVERSITIES ==========
  'babcock university': 'B.U.',
  'covenant university': 'C.U.',
  'american university of nigeria': 'A.U.N.',
  'africa university': 'A.U.',
  'pan-atlantic university': 'P.A.U.',
  'redeemers university': 'R.U.N.',
  'joseph ayo babalola university': 'J.A.B.U.',
  'caleb university': 'C.U.',
  'bowen university': 'B.U.',
  'adeleke university': 'A.U.',
  'landmark university': 'L.U.',
  'crawford university': 'C.U.',
  'benson idahosa university': 'B.I.U.',
  'caritas university': 'C.U.',
  'achievers university': 'A.U.',
  'al- hikmah university': 'A.H.U.',
  'lead city university': 'L.C.U.',
  'madonna university': 'M.U.',
  'tansian university': 'T.U.',
  'veritas university': 'V.U.',
  'western delta university': 'W.D.U.',
  'igbinedion university': 'I.U.',
  'novena university': 'N.U.',
  'ritman university': 'R.U.',
  'salem university': 'S.U.',
  'wellspring university': 'W.U.',
  'wesley university': 'W.U.',
  'christopher university': 'C.U.',
  'kings university': 'K.U.',
  'dominion university': 'D.U.',
  'edwin clark university': 'E.C.U.',
  'european university of nigeria': 'E.U.N.',
  'fountain university': 'F.U.',
  'g odwin university': 'G.U.',
  'greenfield university': 'G.U.',
  'gregory university': 'G.U.',
  'hallmark university': 'H.U.',
  'hezekiah university': 'H.U.',
  'koladaisi university': 'K.U.',
  'michael and cecilia ibru university': 'M.C.I.U.',
  'mountain top university': 'M.T.U.',
  'nigeria turkish nile university': 'N.T.N.U.',
  'paul university': 'P.U.',
  'precious cornerstone university': 'P.C.U.',
  'skyline university': 'S.U.',
  'suman university': 'S.U.',
  'travis university': 'T.U.',
  'university of möa': 'U.M.',

  // ========== FEDERAL POLYTECHNICS ==========
  'federal polytechnic ado-ekiti': 'F.P.A.E.',
  'federal polytechnic bauchi': 'F.P.B.',
  'federal polytechnic bida': 'F.P.B.',
  'federal polytechnic damaturu': 'F.P.D.',
  'federal polytechnic ede': 'F.P.E.',
  'federal polytechnic ekiti': 'F.P.E.',
  'federal polytechnic idah': 'F.P.I.',
  'federal polytechnic ilaro': 'F.P.I.',
  'federal polytechnic mubi': 'F.P.M.',
  'federal polytechnic namoda': 'F.P.N.',
  'federal polytechnic nekede': 'F.P.N.',
  'federal polytechnic offa': 'F.P.O.',
  'federal polytechnic oko': 'F.P.O.',
  'federal polytechnic ukana': 'F.P.U.',
  'federal polytechnic unwana': 'F.P.U.',
  'kaduna polytechnic': 'K.A.D.P.O.L.Y.',
  'hussaini adamu federal polytechnic': 'H.A.F.P.',
  'waziri umaru federal polytechnic': 'W.U.F.P.',
  'yaba college of technology': 'Y.A.B.A.T.E.C.H.',
  'air force institute of technology': 'A.F.I.T.',
  'petroleum training institute': 'P.T.I.',

  // ========== STATE POLYTECHNICS ==========
  'osun state polytechnic': 'O.S.P.O.L.Y.',
  'osun state college of technology': 'O.S.C.T.E.C.H.',
  'kwara state polytechnic': 'K.W.A.R.A.P.O.L.Y.',
  'lagos state polytechnic': 'L.A.S.P.O.L.Y.',
  'plateau state polytechnic': 'P.L.A.P.O.L.Y.',
  'imo state polytechnic': 'I.M.S.P.O.L.Y.',
  'enugu state polytechnic': 'E.S.P.O.L.Y.',
  'benue state polytechnic': 'B.E.N.P.O.L.Y.',
  'gateway polytechnic': 'G.A.T.E.W.A.Y.',
  'the polytechnic igbo-owu': 'I.G.B.O.O.W.U.',
  'kano state polytechnic': 'K.A.N.O.P.O.L.Y.',
  'hassan usman katsina polytechnic': 'H.U.K.P.O.L.Y.',
  'kogi state polytechnic': 'K.O.G.P.O.L.Y.',
  'nasarawa state polytechnic': 'N.A.S.P.O.L.Y.',
  'delta state polytechnic': 'D.E.L.P.O.L.Y.',
  'adamawa state polytechnic': 'A.D.A.P.O.L.Y.',
  'ramat polytechnic': 'R.A.M.A.T.',
  'rukuba polytechnic': 'R.U.K.U.B.A.',
  'mauri tumbar polytechnic': 'M.T.P.',
  'jigawa state polytechnic': 'J.I.G.P.O.L.Y.',
  'taraba state polytechnic': 'T.A.R.P.O.L.Y.',
  'zamfara state polytechnic': 'Z.A.M.P.O.L.Y.',
  'ken saro wiwa polytechnic': 'K.S.W.P.',
  'porte city polytechnic': 'P.C.P.',
  'bolton college of education': 'B.C.E.',

  // ========== COLLEGES OF EDUCATION ==========
  'federal college of education abeokuta': 'F.C.E.A.',
  'federal college of education akoka': 'F.C.E.A.K.O.K.A.',
  'federal college of education bichi': 'F.C.E.B.',
  'federal college of education gusau': 'F.C.E.G.',
  'federal college of education kano': 'F.C.E.K.',
  'federal college of education kontagora': 'F.C.E.K.O.',
  'federal college of education okene': 'F.C.E.O.',
  'federal college of education omoku': 'F.C.E.O.M.',
  'federal college of education pankshin': 'F.C.E.P.',
  'federal college of education potiskum': 'F.C.E.P.O.',
  'federal college of education yola': 'F.C.E.Y.',
  'federal college of education zaria': 'F.C.E.Z.',
  'alvan ikoku federal college of education': 'A.I.F.C.E.',
  'adedeji ogunde college of education': 'A.O.C.E.',
  'emmanuel alayande college of education': 'E.A.C.E.',
  'college of education agbor': 'C.E.A.',
  'college of education akwanga': 'C.E.A.W.',
  'college of education ankpa': 'C.E.A.N.',
  'college of education ekiadolor': 'C.E.E.',
  'college of education warri': 'C.E.W.',
  'college of education ikere ekiti': 'C.E.I.E.',
  'college of education katsina-ala': 'C.E.K.A.',
  'college of education oju': 'C.E.O.',
  'college of education waka-biu': 'C.E.W.B.',
  'college of education zuba': 'C.E.Z.',
  'michael otedola college of primary education': 'M.O.C.P.E.',
  'isa kaita college of education': 'I.K.C.E.',
  'jigawa state college of education': 'J.S.C.E.',
  'kano state college of education and preparatory studies': 'K.S.C.E.P.S.',
  'shehu shagari college of education': 'S.S.C.E.',
  'osun state college of education': 'O.S.C.E.',
  'oyo state college of education': 'O.Y.S.C.E.',
  'college of education lanlate': 'C.E.L.',
  'college of education ilemona': 'C.E.I.',
  'college of education olorunda-are': 'C.E.O.A.',
  'niger state college of education': 'N.S.C.E.',
  'kogi state college of education': 'K.S.C.E.',
  'kaduna state college of education': 'K.D.S.C.E.',
  'college of education gindiri': 'C.E.G.',
  'adamawa state college of education': 'A.S.C.E.',
  'akwa ibom state college of education': 'A.I.S.C.E.',
  'cross river state college of education': 'C.R.S.C.E.',
  'delar college of education': 'D.C.E.',
  'ebonyi state college of education': 'E.S.C.E.',
  'enugu state college of education technical': 'E.S.C.E.T.',
  'isaac jasper boro college of education': 'I.J.B.C.E.',

  // ========== ADDITIONAL PRIVATE UNIVERSITIES ==========
  'african university of science and technology': 'A.U.S.T.',
  'mewar university': 'M.U.',
  'maryam abacha american university': 'M.A.A.U.',
  'capital city university': 'C.C.U.',
  'maranatha university': 'M.U.',
  'nigeria british university': 'N.B.U.',
  'shanon university': 'S.U.',
  'philosophy university': 'P.U.',
  'babcock university teaching hospital': 'B.U.T.H.',
  'atiba university': 'A.U.',
  'chosen university': 'C.U.',
  'eastern palm university': 'E.P.U.',
  'evangel university': 'E.U.',
  'federal university of health sciences abuja': 'F.U.H.S.A.',
  'federal university of health sciences azare': 'F.U.H.S.A.Z.',
  'federal university of health sciences ila-orangun': 'F.U.H.S.I.',
  'federal university of health sciences kebbi': 'F.U.H.S.K.',
  'federal university of health sciences katsina': 'F.U.H.S.K.T.',
  'first technical university': 'F.T.U.',
  'frontier university': 'F.U.',
  'girei university': 'G.U.',
  'glorious vision university': 'G.V.U.',
  'haileybury university': 'H.U.',
  'jane b university': 'J.B.U.',
  'kanem university': 'K.U.',
  'khalifa isiyaku rabi university': 'K.I.R.U.',
  'kingsley ozumba mbadiwe university': 'K.O.M.U.',
  'lighthouse university': 'L.U.',
  'madonna university college of medicine': 'M.U.C.M.',
  'mycshin university': 'M.U.',
  'nigerian british university': 'N.B.U.',
  'northern university': 'N.U.',
  'omolabi university': 'O.U.',
  'open university': 'O.U.',
  'osun state university': 'U.N.I.O.S.U.N.',
  'oyin academy': 'O.A.',
  'pentecost university': 'P.U.',
  'peter university': 'P.U.',
  'propsperity university': 'P.U.',
  'queens university': 'Q.U.',
  'ransome kuti university': 'R.K.U.',
  'royal university': 'R.U.',
  'saisa university': 'S.U.',
  'samuel adegboyega university': 'S.A.U.',
  'save university': 'S.U.',
  'shaka polytechnic': 'S.P.',
  'southern university': 'S.U.',
  'spiritan university': 'S.U.',
  'springs university': 'S.U.',
  'st augustine university': 'S.A.U.',
  'st mary university': 'S.M.U.',
  'sule lamido university': 'S.L.U.',
  'summit university': 'S.U.',
  'sunshine university': 'S.U.',
  'topfaith university': 'T.U.',
  'tower university': 'T.U.',
  'transcendent university': 'T.U.',
  'university of offa': 'U.O.',
  'university of sokoto': 'U.O.S.',
  'westbrook university': 'W.U.',
  'westland university': 'W.U.',

  // ========== ADDITIONAL POLYTECHNICS ==========
  'aba polytechnic': 'A.P.',
  'acca polytechnic': 'A.P.',
  'all saints polytechnic': 'A.S.P.',
  'alpha polytechnic': 'A.P.',
  'amaze polytechnic': 'A.P.',
  'best solution polytechnic': 'B.S.P.',
  'bivan polytechnic': 'B.P.',
  'bolmor polytechnic': 'B.P.',
  'calvary polytechnic': 'C.P.',
  'citi polytechnic': 'C.P.',
  'covenant polytechnic': 'C.P.',
  'crown polytechnic': 'C.P.',
  'dabo academy': 'D.A.',
  'dorben polytechnic': 'D.P.',
  'eastern polytechnic': 'E.P.',
  'fidei polytechnic': 'F.P.',
  'foundation polytechnic': 'F.P.',
  'global polytechnic': 'G.P.',
  'grace polytechnic': 'G.P.',
  'heritage polytechnic': 'H.P.',
  'ibadan city polytechnic': 'I.C.P.',
  'ife city polytechnic': 'I.C.P.',
  'interlink polytechnic': 'I.P.',
  'krisbethel college': 'K.C.',
  'lens polytechnic': 'L.P.',
  'light house polytechnic': 'L.H.P.',
  'mater dei polytechnic': 'M.D.P.',
  'ngbuka polytechnic': 'N.P.',
  'novelty polytechnic': 'N.P.',
  'oka institute': 'O.I.',
  'onit college': 'O.C.',
  'our saviour polytechnic': 'O.S.P.',
  'saf polytechnic': 'S.P.',
  'southern polytechnic': 'S.P.',
  'stars polytechnic': 'S.P.',
  'sure foundation polytechnic': 'S.F.P.',
  'the polytechnic ado-ekiti': 'P.A.E.',
  'tower polytechnic': 'T.P.',
  'trinity polytechnic': 'T.P.',
  'ufuoma polytechnic': 'U.P.',
  'union college': 'U.C.',
  'universal college': 'U.C.',
  'western delta polytechnic': 'W.D.P.',

  // ========== ADDITIONAL COLLEGES OF EDUCATION ==========
  'ad college of education': 'A.C.E.',
  'adeyemi college of education': 'A.C.E.',
  'baichi college of education': 'B.C.E.',
  'bamidele olumilua university of education': 'B.O.U.E.',
  'college of arabic and islamic legal studies': 'C.A.I.L.S.',
  'college of education azare': 'C.E.A.',
  'college of education egbe': 'C.E.E.',
  'college of education hong': 'C.E.H.',
  'college of education ilesa': 'C.E.I.',
  'college of education kafanchan': 'C.E.K.',
  'college of education maru': 'C.E.M.',
  'college of education minna': 'C.E.M.',
  'college of education moro': 'C.E.M.',
  'college of education omuo-ekiti': 'C.E.O.',
  'cornerstone college of education': 'C.C.E.',
  'delta state college of education technical': 'D.S.C.E.T.',
  'eboolawe college of education': 'E.C.E.',
  'edatore college of education': 'E.C.E.',
  'fct college of education': 'F.C.T.C.E.',
  'city college of education': 'C.C.E.',
  'flying dove college of education': 'F.D.C.E.',
  'harvard college of education': 'H.C.E.',
  'ibeno college of education': 'I.C.E.',
  'ijebu-ode college of education': 'I.O.C.E.',
  'international college of education': 'I.C.E.',
  'jibwis college of education': 'J.C.E.',
  'klabele college of education': 'K.C.E.',
  'muftau olanihun college of education': 'M.O.C.E.',
  'nana college of education': 'N.C.E.',
  'nigerian army school of education': 'N.A.S.E.',
  'nwafor orizu college of education': 'N.O.C.E.',
  'peaceland college of education': 'P.C.E.',
  'regina pacis college of education': 'R.P.C.E.',
  'saki city polytechnic': 'S.C.P.',
  'the college of education': 'T.C.E.',
  'unity college of education': 'U.C.E.',
  'world bank college of education': 'W.B.C.E.',

  // ========== SPECIALIZED INSTITUTIONS ==========
  'african think tank university': 'A.T.T.U.',
  'college of nursing and midwifery': 'C.N.M.',
  'elizade university': 'E.U.',
  'federal school of statistics': 'F.S.S.',
  'ikeja college of accountancy': 'I.C.A.',
  'jibwis academy': 'J.A.',
  'moniya business school': 'M.B.S.',
  'nigeria army university biu': 'N.A.U.B.',
  'nigerian college of aviation technology': 'N.C.A.T.',
  'nigerian maritime university': 'N.M.U.',
  'nigerian railway academy': 'N.R.A.',
  'nigerian stock exchange': 'N.S.E.',
  'omega university': 'O.U.',
  'pan african institute': 'P.A.I.',
  'peace university': 'P.U.',

  // ========== MORE PRIVATE UNIVERSITIES (2020+) ==========
  'ace university': 'A.U.',
  'admiralty university': 'A.U.',
  'anchor university': 'A.U.',
  'arthur jarvis university': 'A.J.U.',
  'claretian university': 'C.U.',
  'coal city university': 'C.C.U.',
  'corona university': 'C.U.',
  'divine mercy university': 'D.M.U.',
  'edgerly university': 'E.U.',
  'eight-geo university': 'E.G.U.',
  'faith university': 'F.U.',
  'flux university': 'F.U.',
  'founders university': 'F.U.',
  'franco british university': 'F.B.U.',
  'gerar university': 'G.U.',
  'global innovation university': 'G.I.U.',
  'isaac university': 'I.U.',
  'jesuit university': 'J.U.',
  'johnbosco university': 'J.U.',
  'jubilee university': 'J.U.',
  'kola daisi university': 'K.D.U.',
  'legacy university': 'L.U.',
  'maritim university': 'M.U.',
  'maryam university': 'M.U.',
  'methodist university': 'M.U.',
  'nigerian university of technology': 'N.U.T.',
  'obong university': 'O.U.',
  'palms university': 'P.U.',
  'precious university': 'P.U.',
  'prime university': 'P.U.',
  'pro legislation university': 'P.L.U.',
  'roseman university': 'R.U.',
  'solid rock university': 'S.R.U.',
  'southwestern university': 'S.U.',
  'united africa university': 'U.A.U.',
  'university of cairo': 'U.C.',
  'university of mkar': 'U.M.',
  'virginia university': 'V.U.',
  'wisdom university': 'W.U.',

  // ========== ADDITIONAL STATE UNIVERSITIES ==========
  'adamawa state university': 'A.D.S.U.',
  'bayelsa medical university': 'B.M.U.',
  'borno state university': 'B.O.S.U.',
  'chukwuemeka odumegwu ojukwu university': 'C.O.O.U.',
  'cross river university of technology': 'C.R.U.T.',
  'delta state university of science and technology': 'D.S.U.S.T.',
  'ebonyi state university': 'E.B.S.U.',
  'edo university iyamho': 'E.U.I.',
  'gombe state university': 'G.S.U.',
  'gombe state university of science and technology': 'G.S.U.S.T.',
  'ibeno university': 'I.U.',
  'igbinedion university okada': 'I.U.O.',
  'northwest university': 'N.W.U.',
  'oou university': 'O.U.',
  'osun university': 'O.U.',
  'plateau state university': 'P.S.U.',
  'sokoto state university': 'S.S.U.',
  'sule lamido university kafin hausa': 'S.L.U.K.H.',
  'taraba state university': 'T.S.U.',
  'umaru musa yaradua university': 'U.M.Y.U.',
  'yobe state university': 'Y.S.U.',
  'zamfara state university': 'Z.A.S.U.',

  // ========== SEMINARIES & THEOLOGICAL COLLEGES ==========
  'baptist theological seminary': 'B.T.S.',
  'catholic institute of west africa': 'C.I.W.A.',
  'ecumenical theological seminary': 'E.T.S.',
  'methodist theological institute': 'M.T.I.',
  'nigeria baptist theological seminary': 'N.B.T.S.',
  'spiritan international school of theology': 'S.I.S.T.',
  'spiritan school of philosophy': 'S.S.P.',
  'st augustines major seminary': 'S.A.M.S.',
  'st benedicts monastery': 'S.B.M.',
  'st joseph major seminary': 'S.J.M.S.',
  'st pauls major seminary': 'S.P.M.S.',
  'theological college of northern nigeria': 'T.C.N.N.',
  'trinity theological seminary': 'T.T.S.',
  'west africa theological seminary': 'W.A.T.S.',

  // ========== INNOVATION ENTERPRISE INSTITUTIONS ==========
  'african institute of science and technology': 'A.I.S.T.',
  'christopher technological institute': 'C.T.I.',
  'college of development studies': 'C.D.S.',
  'computer training institute': 'C.T.I.',
  'digital bridge institute': 'D.B.I.',
  'federal training centre': 'F.T.C.',
  'galaxy innovation institute': 'G.I.I.',
  'global technology institute': 'G.T.I.',
  'information technology institute': 'I.T.I.',
  'institute of chartered accountants': 'I.C.A.',
  'institute of management technology': 'I.M.T.',
  'kaduna business school': 'K.B.S.',
  'lagos business school': 'L.B.S.',
  'nigerian institute of journalism': 'N.I.J.',
  'nigerian institute of management': 'N.I.M.',
  'nigerian institute of safety professionals': 'N.I.S.P.',
  'pace innovation institute': 'P.I.I.',
  'pan african university': 'P.A.U.',
  'project management institute': 'P.M.I.',
  'software technology institute': 'S.T.I.',
  'technology incubation centre': 'T.I.C.',

  // ========== VOCATIONAL & TECHNICAL INSTITUTES ==========
  'abuja school of social and political thoughts': 'A.S.S.P.T.',
  'artisans training centre': 'A.T.C.',
  'business training institute': 'B.T.I.',
  'centre for arts and culture': 'C.A.C.',
  'centre for information technology': 'C.I.T.',
  'craft development centre': 'C.D.C.',
  'fashion and design institute': 'F.D.I.',
  'film and broadcast institute': 'F.B.I.',
  'food technology institute': 'F.T.I.',
  'hospitality and tourism institute': 'H.T.I.',
  'industrial training fund': 'I.T.F.',
  'jewellery and design institute': 'J.D.I.',
  'mechanical training centre': 'M.T.C.',
  'national institute of marketing': 'N.I.M.',
  'nigerian institute of building': 'N.I.B.',
  'nigerian institute of estate surveyors': 'N.I.E.S.',
  'nigerian institute of quantity surveyors': 'N.I.Q.S.',
  'nigerian institute of architects': 'N.I.A.',
  'technical training institute': 'T.T.I.',
  'vocational training centre': 'V.T.C.',

  // ========== MORE INSTITUTIONS (2024+) ==========
  'ahmadu bello university zaria': 'A.B.U.',
  'american university of nigeria yola': 'A.U.N.',
  'baze university': 'B.U.',
  'benedictine university': 'B.U.',
  'capital city university kano': 'C.C.U.',
  'city university of technology': 'C.U.T.',
  'eastern university': 'E.U.',
  'federal university of agriculture abeokuta': 'F.U.A.A.',
  'federal university of agriculture makurdi': 'F.U.A.M.',
  'federal university of health sciences otukpo': 'F.U.H.S.O.',
  'federal university of petroleum resources': 'F.U.P.R.E.',
  'federal university of technology babura': 'F.U.T.B.',
  'federal university of technology jalingo': 'F.U.T.J.',
  ' Gregory university': 'G.U.',
  'ira university': 'I.U.',
  'mcpherson university': 'M.U.',
  'nigerian turkish nile university': 'N.T.N.U.',
  'pan atlantic university': 'P.A.U.',
  'skyline university nigeria': 'S.U.N.',
  'university of africa toru orua': 'U.A.T.O.',
  'university of agriculture benue': 'U.A.B.',
  'university of agriculture cross river': 'U.A.C.R.',
  'university of agriculture kebbi': 'U.A.K.',
  'university of agriculture ogwashi-ukwu': 'U.A.O.',
  'university of agriculture osun': 'U.A.O.',
};

/** Abbreviate tenant names with special handling for Nigerian universities
 * 
 * Examples:
 * - 'University of Benin' -> 'U.N.I.B.E.N.'
 * - 'University of Lagos' -> 'U.N.I.L.A.G.'
 * - 'Greenland University' -> 'G.U.' (custom fallback)
 * - 'Wazire' -> 'Wazire' (short names unchanged)
 */
export function abbreviateTenantName(name: string, maxLength: number = 15): string {
  if (!name || name.length <= maxLength) return name || 'Wazire';
  
  // Check for known Nigerian universities (case-insensitive)
  const normalizedName = name.toLowerCase().trim();
  if (NIGERIAN_UNIVERSITIES[normalizedName]) {
    return NIGERIAN_UNIVERSITIES[normalizedName];
  }
  
  // Check for partial matches (e.g., "University of Benin - Main Campus")
  for (const [key, abbreviation] of Object.entries(NIGERIAN_UNIVERSITIES)) {
    if (normalizedName.includes(key)) {
      return abbreviation;
    }
  }
  
  // Custom abbreviation: letter-by-letter format
  const initials = name
    .split(/\s+/)
    .filter(word => word.length > 0)
    .map(word => word[0].toUpperCase());
  return initials.join('.') + '.';
}

/** Get abbreviation without dots for compact display */
export function getCompactAbbreviation(name: string, maxLength: number = 15): string {
  const dotted = abbreviateTenantName(name, maxLength);
  return dotted.replace(/\./g, '');
}
